# Generated by Django 6.0.6 on 2026-07-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_private_key',
            field=models.TextField(blank=True, db_column='private_key', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
